### PR TITLE
Fixed Android section (new gradle config-sepcific code) of README

### LINKED ISSUE #274: Wrong docs for new Gradle system with Android
To package an Android library, the POM file doesn't include dependencies, so a manual override to the  POM must be made. Step 4 of the docs [here](https://github.com/bintray/gradle-bintray-plugin#Getting_Started_Using_the_Plugin) covers that, but there is an error in the following block:

```
    pom.withXml {
        // Iterate over the compile dependencies (we don't want the test ones), adding a <dependency> node for each
        configurations.implementation.allDependencies.each {
           // Ensure dependencies such as fileTree are not included.
           if (it.name != 'unspecified') {
              def dependencyNode = dependenciesNode.appendNode('dependency')
              dependencyNode.appendNode('groupId', it.group)
              dependencyNode.appendNode('artifactId', it.name)
              dependencyNode.appendNode('version', it.version)
           }
        }
      }
```

In the `implementation` (and `api`, for that matter) configuration, there is no `dependenciesNode` variable; it needs to be defined. Here is the above block with the fix (code tested and POM verified):

```
    pom.withXml {
        def dependenciesNode = asNode().getAt('dependencies')[0] ?: asNode().appendNode('dependencies')
        // Iterate over the compile dependencies (we don't want the test ones), adding a <dependency> node for each
        configurations.implementation.allDependencies.each {
           // Ensure dependencies such as fileTree are not included.
           if (it.name != 'unspecified') {
              def dependencyNode = dependenciesNode.appendNode('dependency')
              dependencyNode.appendNode('groupId', it.group)
              dependencyNode.appendNode('artifactId', it.name)
              dependencyNode.appendNode('version', it.version)
           }
        }
      }
```

### PR DESCRIPTION
**Pull request by VedavyasBhat**
Closes #274 and #272

### CODE REVIEW

**Comment by eyalbe4** [comment]
Awesome @VedavyasBhat - thanks you for this!
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge this?

**Comment by VedavyasBhat** [comment]
Hey @eyalbe4 , I've signed the CLA.

**Comment by eyalbe4** [comment]
Thanks @VedavyasBhat!

**Review by Atom1985 — APPROVED** [review]
README.md

**Pull request merged**
