### PR TITLE
Add support for Kotlin DSL

### PR DESCRIPTION
**Pull request by DRSchlaubi**

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thanks you for this addition @DRSchlaubi!
Can you please add tests? You can look at the README for more information. Also, please let me know if you have any questions.

**Comment by DRSchlaubi** [comment]
I've never used groovy and the last time I used the Groovy DSL is 3 years ago so it will take some time to understand the existing tests and probably find a way to not rewrite everything of it

**Comment by eyalbe4** [comment]
@DRSchlaubi,
Let me know if you have any questions about the tests. I'll try to assist.

**Comment by turansky** [comment]
@DRSchlaubi Benefit of new PR - new **clean** commits without ignored files at all
This PR contains ignored files (in first commit), which have not to be.

**Pull request closed without merging**
