### PR TITLE
#13 show how in README

### PR DESCRIPTION
**Pull request by paulvi**

### CODE REVIEW

**Comment by marshallpierce** [comment]
You should instruct users to add to `~/.gradle/gradle.properties` rather than specifying on the command line. If you use the command line, you'll be sharing your api key with anyone who can run 'ps', and it'll leak into your shell history file too.

**Comment by eyalbe4** [comment]
@paulvi , 
Thank you for this documentation improvement.
Can you please sign JFrog's CLA so that I can merge this pull request?
You can do that through [here](http://www.jfrog.com/confluence/display/OSS/How+to+Contribute).

**Comment by eyalbe4** [comment]
@paulvi ,
We need you to approve our [CLA](https://www.jfrog.com/confluence/display/OSS/How+to+Contribute), so that this PR can be merged.
Thanks!

**Comment by paulvi** [comment]
DONE

> Your e-signing of JFrog Contributor License Agreement has been verified. A copy of the signed document is being sent to you.

**Pull request merged**
