### PR TITLE
Add support for Kotlin DSL

### PR DESCRIPTION
**Pull request by DRSchlaubi**
- Add extension to make use of plugin easier when using Kotlin DSL
- Add example to README.md
- Add Kotlin to project

Signed-off-by: Michael Rittmeister <michael@rittmeister.in>

### CODE REVIEW

**Comment by turansky** [comment]
Most files from this PR must be ignored
See #323 for more details

**Comment by DRSchlaubi** [comment]
When #323 is merged I will update this PR

**Comment by eyalbe4** [comment]
#323 is now merged.

**Comment by DRSchlaubi** [comment]
Done

**Comment by turansky** [comment]
New PR will be better in this case

**Pull request closed without merging**
