### PR TITLE
Switch from `Closure` accepting methods to `Action` to be more compat…

### PR DESCRIPTION
**Pull request by mkobit**
…ible with Gradle's `kotlin-dsl`

partially related to https://github.com/bintray/gradle-bintray-plugin/issues/193

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thanks you for this @mkobit!
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by mkobit** [comment]
Done!

**Comment by eyalbe4** [comment]
@mkobit,
When running our tests with the new code we got the below exception.
It looks like with the new code does nor expect to find the *distribution* property inside the *debian* closure.
Here's the *bintray* closure the test uses:
```
bintray {
    apiUrl = bintrayApiUrl
    user = bintrayUser
    key = bintrayKey
    filesSpec {
        from debianDir
        into '.'
    }
    publish = true
    pkg {
        repo = debianRepoName
        name = pkgName
        debian {
            distribution = 'squeeze'
            component = 'main'
            architecture = 'i386,noarch,amd64'
        }
        userOrg = bintrayOrg
        desc =  pkgDesc
        labels = pkgLabels
        licenses = ['Apache-2.0']
        websiteUrl = 'https://github.com/bintray/gradle-bintray-plugin'
        issueTrackerUrl = 'https://github.com/bintray/gradle-bintray-plugin/issues'
        vcsUrl = 'https://github.com/bintray/gradle-bintray-plugin.git'
        githubRepo = 'bintray/gradle-bintray-plugin'
        githubReleaseNotesFile = 'README.md'
        version {
            name = versionName
        }
    }
}
```
And here's the error we got:
```
   FAILURE: Build failed with an exception.

    * Where:
    Script '/Users/eyalb/temp/gradle-bintray-plugin-fork/gradle-bintray-plugin/build/resources/test/gradle/buildFiles/create_debian_package_and_version_with_fileSpec.gradle' line: 17

    * What went wrong:
    A problem occurred evaluating script.
    > No such property: distribution for class: com.jfrog.bintray.gradle.BintrayExtension_Decorated

    * Try:
    Run with --debug option to get more log output.

    * Exception is:
    org.gradle.api.GradleScriptException: A problem occurred evaluating script.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:76)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:156)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:102)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:62)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
        at build_5omg9frulard1cg9ti4ivxkgr$_run_closure3.doCall(/Users/eyalb/temp/gradle-bintray-plugin-fork/gradle-bintray-plugin/build/resources/test/gradle/projects/fileSpec/build.gradle:57)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:819)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:824)
        at org.gradle.api.internal.project.AbstractProject.subprojects(AbstractProject.java:807)
        at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:232)
        at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:127)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at build_5omg9frulard1cg9ti4ivxkgr.run(/Users/eyalb/temp/gradle-bintray-plugin-fork/gradle-bintray-plugin/build/resources/test/gradle/projects/fileSpec/build.gradle:26)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:74)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:156)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:487)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:85)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:55)
    Caused by: groovy.lang.MissingPropertyException: No such property: distribution for class: com.jfrog.bintray.gradle.BintrayExtension_Decorated
        at org.gradle.api.internal.plugins.ExtraPropertiesDynamicObjectAdapter.setProperty(ExtraPropertiesDynamicObjectAdapter.java:46)
        at org.gradle.api.internal.CompositeDynamicObject.setProperty(CompositeDynamicObject.java:122)
        at com.jfrog.bintray.gradle.BintrayExtension_Decorated.setProperty(Unknown Source)
        at com.jfrog.bintray.gradle.BintrayExtension.this$dist$set$1(BintrayExtension.groovy)
        at com.jfrog.bintray.gradle.BintrayExtension$PackageConfig.propertyMissing(BintrayExtension.groovy)
        at com.jfrog.bintray.gradle.BintrayExtension$PackageConfig.setProperty(BintrayExtension.groovy)
        at create_debian_package_and_vers_4aevq5xgf7u9ztmf0j3zxhxbh$_run_closure1_closure3_closure4.doCall(/Users/eyalb/temp/gradle-bintray-plugin-fork/gradle-bintray-plugin/build/resources/test/gradle/buildFiles/create_debian_package_and_version_with_fileSpec.gradle:17)
        at com.sun.proxy.$Proxy40.execute(Unknown Source)
        at org.gradle.api.Action$execute.call(Unknown Source)
        at com.jfrog.bintray.gradle.BintrayExtension$PackageConfig.debian(BintrayExtension.groovy:67)
        at create_debian_package_and_vers_4aevq5xgf7u9ztmf0j3zxhxbh$_run_closure1_closure3.doCall(/Users/eyalb/temp/gradle-bintray-plugin-fork/gradle-bintray-plugin/build/resources/test/gradle/buildFiles/create_debian_package_and_version_with_fileSpec.gradle:16)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.api.Action$execute.call(Unknown Source)
        at com.jfrog.bintray.gradle.BintrayExtension.pkg(BintrayExtension.groovy:35)
        at com.jfrog.bintray.gradle.BintrayExtension_Decorated.pkg(Unknown Source)
        at com.jfrog.bintray.gradle.BintrayExtension_Decorated.pkg(Unknown Source)
        at create_debian_package_and_vers_4aevq5xgf7u9ztmf0j3zxhxbh$_run_closure1.doCall(/Users/eyalb/temp/gradle-bintray-plugin-fork/gradle-bintray-plugin/build/resources/test/gradle/buildFiles/create_debian_package_and_version_with_fileSpec.gradle:13)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)

    BUILD FAILED
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
```

**Comment by mkobit** [comment]
Thanks @eyalbe4 , I'll take a look at it this weekend

**Comment by mkobit** [comment]
I'm going to take a look at this today

**Comment by mkobit** [comment]
I'm able to reproduce with this test (not using other tests because they require some bintray credentials and what not):

```groovy
def "extension DSL test"() {
  given:
  Project project = ProjectBuilder.builder().build()
  project.pluginManager.apply(BintrayPlugin)

  when:
  project.with {
    bintray {
      apiUrl = 'api'
      user = 'user'
      key = 'key'
//      filesSpec {
//        from debianDir
//        into '.'
      }
      publish = true
      pkg {
        repo = 'repo'
        name = 'pkg'
        debian {
          distribution = 'squeeze'
          component = 'main'
          architecture = 'i386,noarch,amd64'
        }
        userOrg = bintrayOrg
        desc =  pkgDesc
        labels = pkgLabels
        licenses = ['Apache-2.0']
        websiteUrl = 'https://github.com/bintray/gradle-bintray-plugin'
        issueTrackerUrl = 'https://github.com/bintray/gradle-bintray-plugin/issues'
        vcsUrl = 'https://github.com/bintray/gradle-bintray-plugin.git'
        githubRepo = 'bintray/gradle-bintray-plugin'
        githubReleaseNotesFile = 'README.md'
        version {
          name = 'versionName'
        }
      }
    }
  }

  then:
  noExceptionThrown()
}
```

I'm wondering if this could be partly because the version of Gradle that Bintray is built with is Gradle 2.4? It looks like it tries to resolve the methods off of the dynamically generated extension class which is not calling the method correctly, so I'll have to look into it some more. Is there a minimum Gradle version that wants to be supported?

**Comment by eyalbe4** [comment]
@mkobit,
After cloning your branch, everything worked for me. I then merged your pull request and tested it again in this repository - the same problem reappeared.
I'm still puzzled by this issue...we have two branches - one of them works and the other doesn't.
Please let me know if you have any insights about this
We may need cancel this commit for now, till we manage to figure this one out.

**Comment by mkobit** [comment]
@eyalbe4 I didnt dive into it any deeper than before, but my initial thoughts are that it is is caused by building and testing against Gradle 2.4

```
    Caused by: groovy.lang.MissingPropertyException: No such property: distribution for class: com.jfrog.bintray.gradle.BintrayExtension_Decorated
        at org.gradle.api.internal.plugins.ExtraPropertiesDynamicObjectAdapter.setProperty(ExtraPropertiesDynamicObjectAdapter.java:46)
        at org.gradle.api.internal.CompositeDynamicObject.setProperty(CompositeDynamicObject.java:122)
        at com.jfrog.bintray.gradle.BintrayExtension_Decorated.setProperty(Unknown Source)
        at com.jfrog.bintray.gradle.BintrayExtension.this$dist$set$1(BintrayExtension.groovy)
        at com.jfrog.bintray.gradle.BintrayExtension$PackageConfig.propertyMissing(BintrayExtension.groovy)
        at com.jfrog.bintray.gradle.BintrayExtension$PackageConfig.setProperty(BintrayExtension.groovy)
        at create_debian_package_and_vers_4aevq5xgf7u9ztmf0j3zxhxbh$_run_closure1_closure3_closure4.doCall(/Users/eyalb/temp/gradle-bintray-plugin-fork/gradle-bintray-plugin/build/resources/test/gradle/buildFiles/create_debian_package_and_version_with_fileSpec.gradle:17)
```

Gradle generates dynamic objects for extension types and it is calling `com.jfrog.bintray.gradle.BintrayExtension$PackageConfig.setProperty(BintrayExtension.groovy)` instead of the method. I have a feeling upgrading Gradle will make the issue more apparent with the nested objects, but I didn't spend any more time with it because I dont know what versions of Gradle this plugin (or the next version) are supposed to be compatible with.

I think it would be generally helpful for the plugin to be updated to a more recent version and use something like [Gradle Test Kit](https://docs.gradle.org/current/userguide/test_kit.html) for testing capabilities and compatibility checks. I didn't spend much time on that part of the infrastructure because I don't know what this is intended to support moving forward.

Hopefully, that is helpful.

**Comment by eyalbe4** [comment]
@mkobit,
I drilled down further into this issue, but unfortunately couldn't make the plugin work with the new API. I used gradle 4.3.1, but it seemed to have no effect.
Since it looked like the issue happens on a second level nesting, I looked for a clue online and
found the following comment [here](https://guides.gradle.org/implementing-gradle-plugins/):

*If you need second- or third-level nesting, you will also have to add overloads that take a Closure, because Gradle cannot instrument nested extensions at the moment.*

I'm curious to know if there's a plugin out there that managed to nest a few extensions (more than one level) using Actions instead of Closures...
For now (till we find a solution), I reverted the code.

**Comment by mkobit** [comment]
Thanks for the followup @eyalbe4 - I'll have to take another stab at this in the next couple weeks. I know you can get the nested extensions to work by adding your own `Action` methods for those extensions. For example, the JUnit 5 Gradle plugin does this below:

* https://github.com/junit-team/junit5/blob/165763b4e99f8aecedd316f278a21d1d4ed8c9ba/junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy#L40-L45
* https://github.com/junit-team/junit5/blob/165763b4e99f8aecedd316f278a21d1d4ed8c9ba/junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformExtension.groovy#L113-L115

**Pull request merged**
