### PR TITLE
Fix publishXXXPublicationToMavenLocal is not invoked

### PR DESCRIPTION
**Pull request by hkhc**
Use ProjectEvaluationListener rather than BuildListener to handle bintray extension block.

It would be too late for BuildListener.projectsEvaluate to add task dependencies.

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thanks you for this @hkhc!

**Comment by LouisCAD** [comment]
When a version including this fix will be published?

**Comment by alicederyn** [comment]
Note that this means gradle-bintray-plugin now races with any other afterEvaluate blocks that attempt to provide it configuration.

**Comment by alicederyn** [comment]
For me this manifested as #170, i.e. the plugin just silently starts failing, and it's not at all obvious why.

**Pull request merged**
